version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.MYSQL
    env_file:
      - env/.env.local
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
