name: Go CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run golintci checks
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...

      - name: setUp env file
        run: |
          mkdir env
          touch env/.env.local
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > env/.env.local
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> env/.env.local
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> env/.env.local
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> env/.env.local
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> env/.env.local

      - name: run docker db
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Build the Go application
        run: go build .

      - name: Run Go tests
        run: go test ./... -v
